# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swag2mcp < Formula
  desc "Bridge OpenAPI/Swagger/Postman specs with LLM agents via MCP"
  homepage "https://github.com/mmadfox/swag2mcp"
  version "0.1.0-alpha.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-alpha.0/swag2mcp_0.1.0-alpha.0_darwin_amd64.tar.gz"
      sha256 "873417d481ccc2bc010b2fb6e9a48aee72d1aeea972f45fafc9c38bdd565f5a2"

      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-alpha.0/swag2mcp_0.1.0-alpha.0_darwin_arm64.tar.gz"
      sha256 "537fbab5149947f3d4dbc0b31ec78c667185c297ce9144b634a301bbfc894809"

      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-alpha.0/swag2mcp_0.1.0-alpha.0_linux_amd64.tar.gz"
      sha256 "fc3e848f1c4ea5e5c25386d0c0217500c3ff85e51461242dea52ad166a184e91"
      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-alpha.0/swag2mcp_0.1.0-alpha.0_linux_arm64.tar.gz"
      sha256 "78a11b9e6fadd2e503b6b7baf06d4bd6704e2dfedce2cbcec61cb91977955f51"
      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
  end
end
