# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crx3 < Formula
  desc "Chrome extension tooling: pack, unpack, download CRX3 extensions"
  homepage "https://github.com/mmadfox/go-crx3"
  version "1.6.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmadfox/go-crx3/releases/download/v1.6.1/crx3_1.6.1_Darwin_x86_64.tar.gz"
      sha256 "fd7c4f055e176a0f674fd18f53597f0f278d05b328bfa225973fb458e281074c"

      define_method(:install) do
        bin.install "crx3"
        bash_completion.install "completions/crx3.bash" => "crx3"
        zsh_completion.install "completions/crx3.zsh" => "_crx3"
        fish_completion.install "completions/crx3.fish"
        man1.install "manpages/crx3.1.gz" if File.exist?("manpages/crx3.1.gz")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmadfox/go-crx3/releases/download/v1.6.1/crx3_1.6.1_Darwin_arm64.tar.gz"
      sha256 "36ea2301d159ff03192e60a6399d7111adbcd15bee6590f06c262c20177d287c"

      define_method(:install) do
        bin.install "crx3"
        bash_completion.install "completions/crx3.bash" => "crx3"
        zsh_completion.install "completions/crx3.zsh" => "_crx3"
        fish_completion.install "completions/crx3.fish"
        man1.install "manpages/crx3.1.gz" if File.exist?("manpages/crx3.1.gz")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/go-crx3/releases/download/v1.6.1/crx3_1.6.1_Linux_x86_64.tar.gz"
      sha256 "f78b023efb39f0d28256794782f188d051e66b85927ba26902a52a9afd19c5c2"
      define_method(:install) do
        bin.install "crx3"
        bash_completion.install "completions/crx3.bash" => "crx3"
        zsh_completion.install "completions/crx3.zsh" => "_crx3"
        fish_completion.install "completions/crx3.fish"
        man1.install "manpages/crx3.1.gz" if File.exist?("manpages/crx3.1.gz")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/go-crx3/releases/download/v1.6.1/crx3_1.6.1_Linux_arm64.tar.gz"
      sha256 "4dd886a07f91d5ecf87a052c294268fa1c40ed781304c35da50690734108071d"
      define_method(:install) do
        bin.install "crx3"
        bash_completion.install "completions/crx3.bash" => "crx3"
        zsh_completion.install "completions/crx3.zsh" => "_crx3"
        fish_completion.install "completions/crx3.fish"
        man1.install "manpages/crx3.1.gz" if File.exist?("manpages/crx3.1.gz")
      end
    end
  end

  test do
    system "#{bin}/crx3 version"
  end
end
