# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crx3 < Formula
  desc "Chrome extension tooling: pack, unpack, download CRX3 extensions"
  homepage "https://github.com/mmadfox/go-crx3"
  version "1.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmadfox/go-crx3/releases/download/v1.7.0/crx3_1.7.0_Darwin_x86_64.tar.gz"
      sha256 "f54a5ea3eb97b0ba787e4a207fe4625cf8413a6ff9b95f467b05cef002832025"

      define_method(:install) do
        bin.install "crx3"
        bash_completion.install "completions/crx3.bash" => "crx3"
        zsh_completion.install "completions/crx3.zsh" => "_crx3"
        fish_completion.install "completions/crx3.fish"
        man1.install "manpages/crx3.1.gz" if File.exist?("manpages/crx3.1.gz")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmadfox/go-crx3/releases/download/v1.7.0/crx3_1.7.0_Darwin_arm64.tar.gz"
      sha256 "dec86805d08a441e2439fdf63302731fa1f7cd2f635db23836d565de07eefda4"

      define_method(:install) do
        bin.install "crx3"
        bash_completion.install "completions/crx3.bash" => "crx3"
        zsh_completion.install "completions/crx3.zsh" => "_crx3"
        fish_completion.install "completions/crx3.fish"
        man1.install "manpages/crx3.1.gz" if File.exist?("manpages/crx3.1.gz")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/go-crx3/releases/download/v1.7.0/crx3_1.7.0_Linux_x86_64.tar.gz"
      sha256 "ef7878aaef1cd2dcfe3f8a79b382b459cbc843d34493f0a77d9bc5c5e8e6c611"
      define_method(:install) do
        bin.install "crx3"
        bash_completion.install "completions/crx3.bash" => "crx3"
        zsh_completion.install "completions/crx3.zsh" => "_crx3"
        fish_completion.install "completions/crx3.fish"
        man1.install "manpages/crx3.1.gz" if File.exist?("manpages/crx3.1.gz")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/go-crx3/releases/download/v1.7.0/crx3_1.7.0_Linux_arm64.tar.gz"
      sha256 "2eb848afa670189940897321260cef531afe5c9d063976196e19abee95eff3f8"
      define_method(:install) do
        bin.install "crx3"
        bash_completion.install "completions/crx3.bash" => "crx3"
        zsh_completion.install "completions/crx3.zsh" => "_crx3"
        fish_completion.install "completions/crx3.fish"
        man1.install "manpages/crx3.1.gz" if File.exist?("manpages/crx3.1.gz")
      end
    end
  end

  test do
    system "#{bin}/crx3 version"
  end
end
