# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swag2mcp < Formula
  desc "Bridge OpenAPI/Swagger/Postman specs with LLM agents via MCP"
  homepage "https://github.com/mmadfox/swag2mcp"
  version "0.1.0-alpha.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-alpha.0/swag2mcp_0.1.0-alpha.0_darwin_amd64.tar.gz"
      sha256 "2138d7f6fadbdbafeb408fa8f3c68b95f894c8d48d37bc914417f200130f856a"

      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-alpha.0/swag2mcp_0.1.0-alpha.0_darwin_arm64.tar.gz"
      sha256 "523bd47f7afeee46b8ce36b41348f737eff09c3a9405c64329b7d4cf7ad3907f"

      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-alpha.0/swag2mcp_0.1.0-alpha.0_linux_amd64.tar.gz"
      sha256 "cef6a80d7dbc836e96b84701bc9a90903124c5c124f9f640a0e0ab278a7fb9b6"
      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-alpha.0/swag2mcp_0.1.0-alpha.0_linux_arm64.tar.gz"
      sha256 "67c71694d2c7e4c1813852c6731db37419696883061fd78efb1a098140b05ebb"
      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
  end
end
