# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swag2mcpMock < Formula
  desc "Mock server for swag2mcp API testing"
  homepage "https://github.com/mmadfox/swag2mcp"
  version "0.1.0-beta.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.4/swag2mcp-mock_0.1.0-beta.4_darwin_amd64.tar.gz"
      sha256 "fc3827ad3a40ed0d0f2dd4288816ab0932ed4e74e147940a05d2b6989534f91b"

      define_method(:install) do
        bin.install "swag2mcp-mock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.4/swag2mcp-mock_0.1.0-beta.4_darwin_arm64.tar.gz"
      sha256 "e250c81194e6bb063f9185f94c44f64bb9c00d129a9a6c108d42673b85ae70ff"

      define_method(:install) do
        bin.install "swag2mcp-mock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.4/swag2mcp-mock_0.1.0-beta.4_linux_amd64.tar.gz"
      sha256 "6810e72b70ec0f3c622f0272b3fbfc363221463731d87f2e6642d20a3987eab5"
      define_method(:install) do
        bin.install "swag2mcp-mock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.4/swag2mcp-mock_0.1.0-beta.4_linux_arm64.tar.gz"
      sha256 "a1c52340c9824f25c941e3eba011db57ef730543640f98200e2d58cab30a6502"
      define_method(:install) do
        bin.install "swag2mcp-mock"
      end
    end
  end
end
