# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swag2mcpMock < Formula
  desc "Mock server for swag2mcp API testing"
  homepage "https://github.com/mmadfox/swag2mcp"
  version "0.1.0-beta.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.6/swag2mcp-mock_0.1.0-beta.6_darwin_amd64.tar.gz"
      sha256 "88e293de43db54a77efe97ca2a63b4f0400cf0ee6517078ebd04092b0699afe6"

      define_method(:install) do
        bin.install "swag2mcp-mock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.6/swag2mcp-mock_0.1.0-beta.6_darwin_arm64.tar.gz"
      sha256 "03eeccdbc36747894ab4b5c05f5628b3c066b263e13aa9fc7e84938055412201"

      define_method(:install) do
        bin.install "swag2mcp-mock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.6/swag2mcp-mock_0.1.0-beta.6_linux_amd64.tar.gz"
      sha256 "e130b475d2f4464fdd896cacc13fefe90ab2e8ef6ca4f9e4567f02f1d7fc8766"
      define_method(:install) do
        bin.install "swag2mcp-mock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.6/swag2mcp-mock_0.1.0-beta.6_linux_arm64.tar.gz"
      sha256 "86a67ffe3f68098e2a036bc8057197926cfc4c877816fb0c4cd62a87cea943b9"
      define_method(:install) do
        bin.install "swag2mcp-mock"
      end
    end
  end
end
