# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swag2mcp < Formula
  desc "Bridge OpenAPI/Swagger/Postman specs with LLM agents via MCP"
  homepage "https://github.com/mmadfox/swag2mcp"
  version "0.1.0-beta.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.4/swag2mcp_0.1.0-beta.4_darwin_amd64.tar.gz"
      sha256 "919a9c080fda3a5d8dbe67c9ff03695dfda7429b73e3d4ee38982ee4aa83df25"

      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.4/swag2mcp_0.1.0-beta.4_darwin_arm64.tar.gz"
      sha256 "63e327c008c3cfa657b3dceb815edbe4768df021ef08b455d9fc5dcbefd9dfa2"

      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.4/swag2mcp_0.1.0-beta.4_linux_amd64.tar.gz"
      sha256 "9f206b38b2c9df926e1022ca312137c592b40f117a0d81134945dc08bf236b03"
      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.4/swag2mcp_0.1.0-beta.4_linux_arm64.tar.gz"
      sha256 "681b97edc3a00ee668108cb04444a17d288aa4bc8a62662759440c08c88f9219"
      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
  end
end
