# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swag2mcp < Formula
  desc "Bridge OpenAPI/Swagger/Postman specs with LLM agents via MCP"
  homepage "https://github.com/mmadfox/swag2mcp"
  version "0.1.0-beta.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.2/swag2mcp_0.1.0-beta.2_darwin_amd64.tar.gz"
      sha256 "bc229688c3b284d98616e20e5ee6416955640d7b4b7726be3e240c334d5971f3"

      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.2/swag2mcp_0.1.0-beta.2_darwin_arm64.tar.gz"
      sha256 "e80792e70de64e3dadcb8b6cf76c8a94d34d6460832d566fb1be2f0b6df6ee28"

      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.2/swag2mcp_0.1.0-beta.2_linux_amd64.tar.gz"
      sha256 "4536f1032bbea0893f7f61afc7668ec13f16b11220ea0e135dda1d2aae022227"
      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-beta.2/swag2mcp_0.1.0-beta.2_linux_arm64.tar.gz"
      sha256 "b248013d79b15caa34ea3bc6ac64cce449a1d7c2d09de92da47005bedd945de3"
      define_method(:install) do
        bin.install "swag2mcp"
      end
    end
  end
end
