# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swag2mcpMock < Formula
  desc "Mock server for swag2mcp API testing"
  homepage "https://github.com/mmadfox/swag2mcp"
  version "0.1.0-alpha.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-alpha.0/swag2mcp-mock_0.1.0-alpha.0_darwin_amd64.tar.gz"
      sha256 "1e2252875daaf26f7a4616d4f1d0be1938c20e1091b125a877d22c9a53bf40e7"

      define_method(:install) do
        bin.install "swag2mcp-mock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-alpha.0/swag2mcp-mock_0.1.0-alpha.0_darwin_arm64.tar.gz"
      sha256 "200857b8a03a32ff64b415a2a626d00d9526221cfb8c65a881cc5b2cdaf32265"

      define_method(:install) do
        bin.install "swag2mcp-mock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-alpha.0/swag2mcp-mock_0.1.0-alpha.0_linux_amd64.tar.gz"
      sha256 "3d1dadc45b34dcf075cda4275a46058c701968324ec7cb95249f134dd854de3e"
      define_method(:install) do
        bin.install "swag2mcp-mock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mmadfox/swag2mcp/releases/download/v0.1.0-alpha.0/swag2mcp-mock_0.1.0-alpha.0_linux_arm64.tar.gz"
      sha256 "b967fd5992fe1828673fec545faad8c504382a07d7251cf4b561c898d082faaf"
      define_method(:install) do
        bin.install "swag2mcp-mock"
      end
    end
  end
end
